# Generated by Django 6.1 on 2026-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_bolo'),
        ),
    ]
